spring:
  application:
    name: fileservice
  profiles:
    active: s3

storage:
  provider: ${STORAGE_PROVIDER:s3}
  bucket: ${STORAGE_BUCKET}
  region: ${STORAGE_REGION}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}
  signed-url-expiry: ${STORAGE_SIGNED_URL_EXPIRY:15m}